//JS
export const JSSTRICT = '\"use strict\"'
export const ITEMSPACING = '\n\n\n'
export const JSROOM = 'Room'
export const JSITEM = 'Item'
export const JSTAKABLE = 'TAKEABLE()'
export const JSPLAYER = 'PLAYER()'
export const JSNPC = 'NPC()'
export const JSCONTAINER = 'CONTAINER()'
export const JSSURFACE = 'SURFACE()'
export const JSOPENABLE = 'OPENABLE()'
export const JSLOCKED = 'LOCKED_WITH()'
export const JSWERABLE = 'WEARABLE'
export const JSEDIBLE = 'EDIBLE()'
export const JSCOUNTABLE = 'COUNTABLE()'
export const JSFURNITURE = 'FURNITURE()'
export const JSSWITCHABLE = 'SWITCHABLE()'
export const JSCOMPONENT = 'COMPONENT()'

//XML
export const XMLOBJECT = 'object'
export const XMLCOMMAND = 'command'
export const XMLFUNCTION = 'function'
export const XMLTYPE = 'type'
