export const ICON_SETTINGS = 'sliders-h'
export const ICON_ROOM = 'location-arrow'
export const ICON_ITEM = 'seedling'
export const ICON_STUB = 'folder'
export const ICON_FUNCTION = 'code'
export const ICON_COMMAND = 'terminal'
export const ICON_TMPLATES = 'clone'
